name: Selenium Tests

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  test:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        browser: [CHROME, FIREFOX, EDGE]

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Maven Packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}

      - name: Run Selenium Tests
        run: mvn clean test -Psmoke -Pheadless -Dbrowser=chrome  -Dbase.url=https://the-internet.herokuapp.com

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results
    
    
    
    